name: test
on: [workflow_dispatch]
jobs:
  get_tags:
    runs-on: ubuntu-latest
    steps:
      - name: get tags
        run: |
          tags_array=($(curl -L -s 'https://registry.hub.docker.com/v2/repositories/library/percona/tags'|jq '."results"[]["name"]'))
          echo ${tags_array[*]}
          sort -V <<<${tags_array[*]}
