name: test
on: [workflow_dispatch]
jobs:
  get-tags:
    runs-on: ubuntu-latest
    outputs:
        repos: ${{ steps.get-repo-with-tags.outputs.repos }}
    steps:
      - name: Get tags
        id: get-repo-with-tags
        run: |
          # Make a GET request to Docker Hub API for Percona repositories
          response=$(curl -s "https://hub.docker.com/v2/repositories/percona/?page_size=100")

          # Extract the repository names from the response using jq
          repos=$(echo "$response" | jq -r '."results"[]["name"]')

          repo_json="["

          # Iterate over each repository and retrieve the five latest tags
          for repo in $repos; do
              tags_array=()
              link="https://hub.docker.com/v2/repositories/percona/${repo}/tags/?page_size=100"
              while [ "$link" != "null" ]; do
                  tags_response=$(curl -s $link)
                  link=$(echo "$tags_response" | jq -r '.next')
                  tags=$(echo "$tags_response" | jq -r '."results"[]["name"]')
                  tags_array+=(${tags[@]})
                      done
              tags_array=($(printf "%s\n" "${tags_array[@]}" | sort -V | tail -n 5))

              for tag in ${tags_array[@]}; do
                  repo_json+="{\"repository\": \"$repo\", \"tag\": \"$tag\"},"
              done
          done
          repo_json=${repo_json%?}
          repo_json+="]"
          echo "repos=$repo_json" >> $GITHUB_OUTPUT
  scan-repos:
    permissions: write-all
    runs-on: ubuntu-latest
    needs: get-tags
    strategy:
      matrix:
        include: ${{ fromJSON(needs.get-tags.outputs.repos) }}
    steps:
      - name: Install Trivy
        run: |
          wget https://github.com/aquasecurity/trivy/releases/download/v0.29.2/trivy_0.29.2_Linux-64bit.deb
          sudo dpkg -i trivy_0.29.2_Linux-64bit.deb
      - name: Run Trivy vulnerability scanner
        run: |
          trivy image --format template --template "@/usr/local/share/trivy/templates/html.tpl" \
          -o ${{ matrix.repository }}_${{ matrix.tag }}-report.html percona/${{ matrix.repository }}:${{ matrix.tag }}
      - name: Upload report artifact
        uses: actions/upload-artifact@v3
        with:
          name: trivy-scan-report
          path: ./${{ matrix.repository }}_${{ matrix.tag }}-report.html
      
      
      
      
