name: test
on: [workflow_dispatch]
jobs:
  get_tags:
    runs-on: ubuntu-latest
    steps:
      - name: get tags
        run: |
          my_array=(curl 'https://registry.hub.docker.com/v2/repositories/library/centos/tags/list'|jq '."results"[]["name"]')
          
          echo my_array[0]
          echo my_array[1]
